name: Azure ARM

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
      - uses: actions/checkout@v3

      # Log into Azure
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy ARM template
      - name: Run ARM deploy
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: rg-migration-scus-001
          scope: resourcegroup
          template: ./template.json
          parameters: |
            {
              "enterpriseScaleCompanyPrefix": { "value": "RootSivale" },
              "singlePlatformSubscriptionId": { "value": "a219a903-c314-432f-b8e6-a3a55abde125" },
              "telemetryOptOut": { "value": "Yes" },
              "enableLogAnalytics": { "value": "Yes" },
              "retentionInDays": { "value": "30" },
              "managementSubscriptionId": { "value": "a219a903-c314-432f-b8e6-a3a55abde125" },
              "enableChangeTracking": { "value": "Yes" },
              "enableUpdateMgmt": { "value": "Yes" },
              "enableVmInsights": { "value": "Yes" },
              "enableAsc": { "value": "Yes" },
              "emailContactAG": { "value": "Administrator@devsivale.onmicrosoft.com" },
              "enableAscForServers": { "value": "DeployIfNotExists" }
            }

      # Output containerName variable from template
      - run: echo ${{ steps.deploy.outputs.containerName }}
